{% set version = "1.5.3.1" %}

package:
  name: bioconductor-dada2
  version: {{ version }}
source:
  fn: dada2-{{ version }}.tar.gz
  url: https://github.com/benjjneb/dada2/archive/explicit-SSE.tar.gz
  sha256: 1592e261f701a5eb4e73839ed9c8dd2cc02a8ac9794c6f778f5b538d1ccdc3d7
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biostrings >=2.32.1'
    - 'bioconductor-shortread >=1.24.0'
    - r-base
    - 'r-data.table >=1.9.4'
    - 'r-ggplot2 >=1.0'
    - 'r-rcpp >=0.11.2'
    - 'r-rcppparallel >=4.3.0'
    - 'r-reshape2 >=1.4.1'
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - 'bioconductor-biostrings >=2.32.1'
    - 'bioconductor-shortread >=1.24.0'
    - r-base
    - 'r-data.table >=1.9.4'
    - 'r-ggplot2 >=1.0'
    - 'r-rcpp >=0.11.2'
    - 'r-rcppparallel >=4.3.0'
    - 'r-reshape2 >=1.4.1'
test:
  commands:
    - '$R -e "library(''dada2'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/dada2.html
  license: LGPL-3
  summary: 'The dada2 package provides "OTU picking" functionality, but instead of
    picking OTUs the DADA2 algorithm exactly infers samples sequences. The dada2 pipeline
    starts from demultiplexed fastq files, and outputs inferred sample sequences and
    associated abundances after removing substitution and chimeric errors. Taxonomic
    classification is also available via a native implementation of the RDP classifier
    method.'
